=== api-evangelist/amazon-codestar/json-schema/codestar-describe-project-result-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-codestar/refs/heads/main/json-schema/codestar-describe-project-result-schema.json",
  "title": "DescribeProjectResult",
  "description": "DescribeProjectResult schema from AWS CodeStar API",
  "type": "object",
  "properties": {
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectName"
        },
        {
          "description": "The display name for the project."
        }
      ]
    },
    "id": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectId"
        },
        {
          "description": "The ID of the project."
        }
      ]
    },
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectArn"
        },
        {
          "description": "The Amazon Resource Name (ARN) for the project."
        }
      ]
    },
    "description": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectDescription"
        },
        {
          "description": "The description of the project, if any."
        }
      ]
    },
    "clientRequestToken": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ClientRequestToken"
        },
        {
          "description": "A user- or system-generated token that identifies the entity that requested project creation. "
        }
      ]
    },
    "createdTimeStamp": {
      "allOf": [
        {
          "$ref": "#/components/schemas/CreatedTimestamp"
        },
        {
          "description": "The date and time the project was created, in timestamp format."
        }
      ]
    },
    "stackId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StackId"
        },
        {
          "description": "The ID of the primary stack in AWS CloudFormation used to generate resources for the project."
        }
      ]
    },
    "projectTemplateId": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectTemplateId"
        },
        {
          "description": "The ID for the AWS CodeStar project template used to create the project."
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ProjectStatus"
        },
        {
          "description": "The project creation or deletion status."
        }
      ]
    }
  }
}

=== api-evangelist/amazon-codestar/examples/codestar-describe-project-result-example.json
{
  "name": "example-name",
  "id": "id-abc123",
  "arn": "arn:aws:codestar:us-east-1:123456789012:project/my-project",
  "description": "Example description for this resource.",
  "clientRequestToken": "example-string",
  "createdTimeStamp": "example-string",
  "stackId": "id-abc123",
  "projectTemplateId": "my-project",
  "status": "active"
}
